-- OpenRBMK configuration file
-- Generated by the OpenRBMK settings interface

return {
  shutdownTempC          = 900,                                    -- °C hard SCRAM
  scramPredictTempC      = 1500,                                   -- °C anticipatory SCRAM
  tempStableReq          = 5.0,                                    -- seconds prediction must persist
  maxTargetTempC         = 1100,                                   -- °C full AUTO authority reached at (this - 300)
  updateEvery            = 0.1,                                    -- seconds
  tempOffsetC            = 0,                                      -- °C display / control offset
  adaptiveControl        = true,                                   -- enable adaptive AUTO clamp logic
  fluxScram              = 1300,                                   -- hard SCRAM on prompt excursion
  withdrawStep           = 1,                                      -- % per cycle (out)
  insertStep             = 6,                                      -- % per cycle (in)
  rodHoldCold            = 10,                                     -- % minimum at cold
  heaterExportOkMb       = 2,                                      -- mB/t heater export threshold
  titleOverride          = nil,                                    -- nil = default title
  versionOverride        = nil,                                    -- nil = default version
  defaultMode            = "AUTO",                                 -- SCRAM, MANUAL, AUTO
  scramRedstoneIo        = 3,                                      -- side number
  scramResetRedstoneIo   = 2,                                      -- side number
  modeSwitchRedstoneIo   = 3,                                      -- side number
  manualControlRedstoneIo= 2,                                      -- side number
  redstoneMainAddr       = "d70380a6-aa4c-425b-b934-867dbc4b3eb5", -- SCRAM + reset component address
  redstoneAuxAddr        = "a0a556a7-4602-4eaf-a61a-d479de8805bb", -- mode switch component address
  redstoneManualAddr     = "bab2a090-a584-4eef-809b-ce26ecdf2b68", -- manual control component address
}
